// clip-prompt.test.mjs — positive-evidence integration tests for pillar (c)
// "prompt-based clipping" of docs/PLAN-v0.3.0.md §4.4.
//
// All four scenarios route through bin/cf-clip with CF_CLIP_SCOUT_MOCK
// pointed at tests/mocks/clip-scout-mock.mjs. The mock is deterministic
// (no Date.now, no Math.random) so a re-run produces byte-identical
// candidates.json and these assertions stay stable.
//
// Skip-on-missing: the fixture transcript is generated by
// tests/fixtures/build-fixtures.mjs. If it isn't present (fresh checkout
// before `npm run build-fixtures`), each test reports SKIP rather than
// fails — matching the success-path.test.mjs pattern. ffmpeg is NOT
// required for this test suite (pure transcript-driven, no render).

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, rmSync } from 'node:fs';
import { resolve, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { tmpdir } from 'node:os';

const PLUGIN_ROOT = resolve(fileURLToPath(import.meta.url), '../../..');
const CF_CLIP    = resolve(PLUGIN_ROOT, 'bin/cf-clip');
const MOCK_SCOUT = resolve(PLUGIN_ROOT, 'tests/mocks/clip-scout-mock.mjs');
const FIXTURE    = resolve(PLUGIN_ROOT, 'tests/fixtures/topic-transcript-60s.json');

const HAS_FIXTURE = existsSync(FIXTURE);
const HAS_MOCK    = existsSync(MOCK_SCOUT);
const HAS_DISPATCH = existsSync(CF_CLIP);
const SKIP = !HAS_FIXTURE ? 'topic-transcript-60s.json missing — run `npm run build-fixtures`'
           : !HAS_MOCK ? 'tests/mocks/clip-scout-mock.mjs missing'
           : !HAS_DISPATCH ? 'bin/cf-clip missing'
           : null;

// Word-boundary anchored so substrings like "company" don't accidentally
// match the cooking bag's `cook` token. Same shape the mock uses internally.
const CAREER_RE  = /\b(career|job|quit|salary|raise|promotion)\b/i;
const FITNESS_RE = /\b(fitness|gym|squat|cardio|protein|rep|reps)\b/i;
const COOKING_RE = /\b(cook|cooks|cooking|recipe|sauce|onion|pan|knife)\b/i;

function runDispatcher({ workDir, prompt = null }) {
  mkdirSync(workDir, { recursive: true });
  const outPath = join(workDir, 'candidates.json');
  const args = [
    CF_CLIP,
    '--transcript', FIXTURE,
    '--output', outPath,
    '--slug', 'clip-prompt-test',
  ];
  if (prompt !== null) {
    args.push('--prompt', prompt);
  }
  const r = spawnSync(process.execPath, args, {
    encoding: 'utf-8',
    env: { ...process.env, CF_CLIP_SCOUT_MOCK: MOCK_SCOUT },
  });
  assert.equal(r.status, 0,
    'cf-clip must exit 0 on every documented path; stderr=' + (r.stderr || ''));
  assert.ok(existsSync(outPath), 'candidates.json must exist after cf-clip run');
  const data = JSON.parse(readFileSync(outPath, 'utf-8'));
  return { data, outPath };
}

test('clip-prompt: no --prompt → candidates span all three topics (fitness, career, cooking)',
  { skip: SKIP || false, timeout: 30_000 }, () => {
    const work = join(tmpdir(), 'cf-clip-prompt-none-' + Date.now());
    try {
      const { data } = runDispatcher({ workDir: work });
      assert.ok(Array.isArray(data.candidates) && data.candidates.length >= 3,
        'baseline must return at least 3 candidates; got ' + (data.candidates?.length ?? 'none'));
      const allText = data.candidates.map((c) => c.transcript_excerpt || '').join(' ');
      assert.match(allText, FITNESS_RE,
        'baseline candidates must include a fitness-keyword span; got: ' + allText.slice(0, 240));
      assert.match(allText, CAREER_RE,
        'baseline candidates must include a career-keyword span; got: ' + allText.slice(0, 240));
      assert.match(allText, COOKING_RE,
        'baseline candidates must include a cooking-keyword span; got: ' + allText.slice(0, 240));
      // No warning expected on the baseline path.
      assert.ok(!data.warning, 'baseline should not emit a warning; got ' + JSON.stringify(data.warning));
      assert.equal(data.fallback_used, false, 'baseline fallback_used must be false');
    } finally {
      try { rmSync(work, { recursive: true, force: true }); } catch {}
    }
  });

test('clip-prompt: --prompt "career advice" → only career candidates, no fitness or cooking',
  { skip: SKIP || false, timeout: 30_000 }, () => {
    const work = join(tmpdir(), 'cf-clip-prompt-career-' + Date.now());
    try {
      const { data } = runDispatcher({ workDir: work, prompt: 'career advice' });
      assert.ok(Array.isArray(data.candidates) && data.candidates.length > 0,
        'prompt filter must return at least one career candidate; got ' + (data.candidates?.length ?? 'none'));
      for (const c of data.candidates) {
        const excerpt = c.transcript_excerpt || '';
        assert.match(excerpt, CAREER_RE,
          'every candidate must match career bag; got: "' + excerpt + '"');
        assert.doesNotMatch(excerpt, FITNESS_RE,
          'no candidate may match fitness bag under --prompt "career advice"; got: "' + excerpt + '"');
        assert.doesNotMatch(excerpt, COOKING_RE,
          'no candidate may match cooking bag under --prompt "career advice"; got: "' + excerpt + '"');
      }
      assert.equal(data.fallback_used, false,
        'on-topic prompt filter is a soft path; fallback_used must be false');
    } finally {
      try { rmSync(work, { recursive: true, force: true }); } catch {}
    }
  });

test('clip-prompt: --prompt "underwater basket weaving" → honest empty + warning',
  { skip: SKIP || false, timeout: 30_000 }, () => {
    const work = join(tmpdir(), 'cf-clip-prompt-zero-' + Date.now());
    try {
      const { data } = runDispatcher({ workDir: work, prompt: 'underwater basket weaving' });
      assert.deepEqual(data.candidates, [],
        'zero-match prompt must return candidates:[]; got ' + JSON.stringify(data.candidates));
      assert.ok(data.warning && typeof data.warning === 'object',
        'zero-match must surface a structured warning object; got ' + JSON.stringify(data.warning));
      assert.equal(data.warning.code, 'no_match',
        'warning.code must be "no_match"; got "' + data.warning.code + '"');
      assert.ok(typeof data.warning.message === 'string' && data.warning.message.length > 0,
        'warning.message must be a non-empty string; got ' + JSON.stringify(data.warning.message));
      // CRITICAL: "no_match" is a soft warning, NOT a hard fallback.
      assert.equal(data.fallback_used, false,
        'fallback_used must stay false on no_match — it is a soft warning, not a degradation');
    } finally {
      try { rmSync(work, { recursive: true, force: true }); } catch {}
    }
  });

test('clip-prompt: candidates re-ranked by virality desc within filtered set',
  { skip: SKIP || false, timeout: 30_000 }, () => {
    const work = join(tmpdir(), 'cf-clip-prompt-rerank-' + Date.now());
    try {
      const { data } = runDispatcher({ workDir: work, prompt: 'career advice' });
      assert.ok(data.candidates.length >= 2,
        're-rank invariant needs at least 2 candidates to be meaningful; got ' + data.candidates.length);
      let prev = Infinity;
      for (const c of data.candidates) {
        assert.ok(typeof c.virality === 'number',
          'every candidate must carry a numeric virality; got ' + typeof c.virality);
        assert.ok(c.virality <= prev,
          're-rank invariant: virality must be monotonically descending — got ' +
          c.virality + ' after ' + prev + ' (candidate ' + c.id + ')');
        prev = c.virality;
      }
      // IDs must be re-assigned c01.. in the new sorted order.
      data.candidates.forEach((c, i) => {
        const expected = 'c' + String(i + 1).padStart(2, '0');
        assert.equal(c.id, expected,
          'IDs must be re-assigned in sorted order; got ' + c.id + ' at index ' + i +
          ' (expected ' + expected + ')');
      });
    } finally {
      try { rmSync(work, { recursive: true, force: true }); } catch {}
    }
  });
