// reframe.test.mjs — integration test for bin/cf-reframe end-to-end.
// Generates a 5-second test video on first run via ffmpeg lavfi, then runs
// cf-reframe against it and validates the output schema.
//
// Skips cleanly if ffmpeg isn't available.

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { execSync, spawnSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, writeFileSync, rmSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const PLUGIN_ROOT = resolve(fileURLToPath(import.meta.url), '../../..');
const DEMO_PATH = resolve(PLUGIN_ROOT, 'samples/demo-5s.mp4');
const OUT_PATH = resolve(PLUGIN_ROOT, '/tmp/cf-reframe-itest.json');

function which(cmd) {
  try {
    return execSync('command -v ' + cmd, { stdio: ['ignore', 'pipe', 'ignore'] }).toString().trim();
  } catch { return null; }
}

const HAS_FFMPEG = !!which('ffmpeg');

function ensureDemoVideo() {
  if (existsSync(DEMO_PATH)) return true;
  if (!HAS_FFMPEG) return false;
  mkdirSync(dirname(DEMO_PATH), { recursive: true });
  // 5 seconds, 1280x720, 30fps, with a moving rectangle to simulate motion.
  // testsrc produces visible content; MediaPipe won't detect a face here,
  // so the test exercises the FALLBACK path — which is exactly what we want
  // to verify (graceful degradation is the contract).
  const r = spawnSync('ffmpeg', [
    '-y', '-hide_banner', '-loglevel', 'error',
    '-f', 'lavfi', '-i', 'testsrc=duration=5:size=1280x720:rate=30',
    '-c:v', 'libx264', '-preset', 'ultrafast', '-crf', '28',
    '-pix_fmt', 'yuv420p',
    DEMO_PATH,
  ]);
  return r.status === 0;
}

test('cf-reframe end-to-end on demo video (skipped when ffmpeg missing)', { skip: !HAS_FFMPEG, timeout: 30_000 }, async () => {
  const ok = ensureDemoVideo();
  assert.ok(ok, 'demo video should exist or be generated by ffmpeg');

  // Run cf-reframe synchronously; record wall-clock.
  const t0 = Date.now();
  const r = spawnSync('node', [
    resolve(PLUGIN_ROOT, 'bin/cf-reframe'),
    DEMO_PATH,
    '--output', OUT_PATH,
    '--sample-fps', '4',
  ], { encoding: 'utf-8' });
  const elapsed = Date.now() - t0;

  assert.equal(r.status, 0, 'cf-reframe should exit 0 even when no faces found\n' + r.stderr);
  assert.ok(elapsed < 20_000, 'should complete in <20s wall clock (got ' + elapsed + 'ms)');

  // Parse output
  const out = JSON.parse(readFileSync(OUT_PATH, 'utf-8'));

  // Schema validation — must remain compatible with cf-ffmpeg.
  assert.equal(out.version, 2, 'crop_path.json should be version 2');
  assert.equal(out.source_w, 1280);
  assert.equal(out.source_h, 720);
  assert.equal(out.target_w, 1080);
  assert.equal(out.target_h, 1920);
  assert.ok(Array.isArray(out.samples), 'samples must be an array');
  assert.ok(out.samples.length > 0, 'samples must be non-empty');

  // Every sample must have the v1-compatible fields cf-ffmpeg reads.
  for (const s of out.samples) {
    assert.equal(typeof s.t_ms,  'number');
    assert.equal(typeof s.cx,    'number');
    assert.equal(typeof s.cy,    'number');
    assert.equal(typeof s.scale, 'number');
    assert.ok(s.cx >= 0 && s.cx <= out.source_w, 'cx must be within source bounds');
    assert.ok(s.cy >= 0 && s.cy <= out.source_h, 'cy must be within source bounds');
  }

  // testsrc has no faces, so fallback should kick in.
  assert.equal(out.fallback_used, true, 'expected center/topcrop fallback on testsrc input');
  assert.match(out.detector, /(fallback|mediapipe)/);

  // Cleanup
  try { rmSync(OUT_PATH); } catch {}
});

test('cf-reframe accepts --in / --out (v0.1.0 form) for backwards compat', { skip: !HAS_FFMPEG, timeout: 30_000 }, () => {
  ensureDemoVideo();
  const r = spawnSync('node', [
    resolve(PLUGIN_ROOT, 'bin/cf-reframe'),
    '--in', DEMO_PATH,
    '--out', OUT_PATH,
    '--start-ms', '0',
    '--end-ms', '2000',
    '--fps', '4',
  ], { encoding: 'utf-8' });
  assert.equal(r.status, 0, r.stderr);
  const out = JSON.parse(readFileSync(OUT_PATH, 'utf-8'));
  assert.equal(out.version, 2);
  assert.ok(out.samples.length > 0);
  try { rmSync(OUT_PATH); } catch {}
});

test('cf-reframe --target-aspect 1:1 produces square target dims', { skip: !HAS_FFMPEG, timeout: 30_000 }, () => {
  ensureDemoVideo();
  const r = spawnSync('node', [
    resolve(PLUGIN_ROOT, 'bin/cf-reframe'),
    DEMO_PATH,
    '--output', OUT_PATH,
    '--target-aspect', '1:1',
    '--sample-fps', '4',
  ], { encoding: 'utf-8' });
  assert.equal(r.status, 0, r.stderr);
  const out = JSON.parse(readFileSync(OUT_PATH, 'utf-8'));
  assert.equal(out.target_w, out.target_h, 'square target → equal w and h');
  try { rmSync(OUT_PATH); } catch {}
});

test('cf-reframe --speaker-map honors explicit mapping end-to-end', { skip: !HAS_FFMPEG, timeout: 30_000 }, () => {
  ensureDemoVideo();
  // Synthesize a minimal transcript that ActiveSpeakerTracker can read.
  const txPath = '/tmp/cf-reframe-itest-tx.json';
  writeFileSync(txPath, JSON.stringify({
    version: 1, engine: 'test', language: 'en', duration_s: 5,
    speakers: [{ id: 0, label: 'A' }, { id: 1, label: 'B' }],
    words: [
      { w: 'hello', start_ms: 0,    end_ms: 1500, speaker: 0, confidence: 1.0 },
      { w: 'world', start_ms: 2000, end_ms: 4500, speaker: 1, confidence: 1.0 },
    ],
    sentences: [],
  }));

  const r = spawnSync('node', [
    resolve(PLUGIN_ROOT, 'bin/cf-reframe'),
    DEMO_PATH,
    '--output', OUT_PATH,
    '--sample-fps', '4',
    '--transcript', txPath,
    '--speaker-map', '0:left,1:right',
  ], { encoding: 'utf-8' });
  assert.equal(r.status, 0, r.stderr);

  const out = JSON.parse(readFileSync(OUT_PATH, 'utf-8'));
  // The output should record what was parsed even though the testsrc video
  // triggers the no-face fallback. This proves the flag plumbing works
  // end-to-end (parse → tracker → output metadata).
  assert.ok(out.speaker_map, 'speaker_map should be in output');
  assert.deepEqual(out.speaker_map['0'], { x: 0.25, y: 0.5 }, 'speaker 0 → left slot');
  assert.deepEqual(out.speaker_map['1'], { x: 0.75, y: 0.5 }, 'speaker 1 → right slot');

  try { rmSync(OUT_PATH); rmSync(txPath); } catch {}
});

test('cf-reframe --speaker-map with numeric form is parsed correctly', { skip: !HAS_FFMPEG, timeout: 30_000 }, () => {
  ensureDemoVideo();
  const txPath = '/tmp/cf-reframe-itest-tx2.json';
  writeFileSync(txPath, JSON.stringify({
    version: 1, engine: 'test', language: 'en', duration_s: 5,
    speakers: [{ id: 0, label: 'A' }],
    words: [{ w: 'hi', start_ms: 0, end_ms: 1000, speaker: 0, confidence: 1.0 }],
    sentences: [],
  }));

  const r = spawnSync('node', [
    resolve(PLUGIN_ROOT, 'bin/cf-reframe'),
    DEMO_PATH,
    '--output', OUT_PATH,
    '--sample-fps', '4',
    '--transcript', txPath,
    '--speaker-map', '0:0.3,0.4',
  ], { encoding: 'utf-8' });
  assert.equal(r.status, 0, r.stderr);

  const out = JSON.parse(readFileSync(OUT_PATH, 'utf-8'));
  assert.ok(out.speaker_map);
  assert.equal(out.speaker_map['0'].x, 0.3);
  assert.equal(out.speaker_map['0'].y, 0.4);
  try { rmSync(OUT_PATH); rmSync(txPath); } catch {}
});

test('cf-reframe --fallback topcrop offsets vertical center upward', { skip: !HAS_FFMPEG, timeout: 30_000 }, () => {
  ensureDemoVideo();
  const r = spawnSync('node', [
    resolve(PLUGIN_ROOT, 'bin/cf-reframe'),
    DEMO_PATH,
    '--output', OUT_PATH,
    '--fallback', 'topcrop',
    '--sample-fps', '4',
  ], { encoding: 'utf-8' });
  assert.equal(r.status, 0, r.stderr);
  const out = JSON.parse(readFileSync(OUT_PATH, 'utf-8'));
  if (out.fallback_used) {
    // topcrop puts cy at ~38% of source_h
    const expectedCy = Math.floor(out.source_h * 0.38);
    assert.equal(out.samples[0].cy, expectedCy, 'topcrop should set cy to upper third');
  }
  try { rmSync(OUT_PATH); } catch {}
});
